module Constants::Billing
  SUBACCOUNT_PRICE_ID = ENV["NOTESPRO_SUBACCOUNT_PRICE"]

  MULTISITE_PRODUCT_ID = ENV["NOTESPRO_MULTISITE_PRODUCT"]
  BASE_PRODUCT_ID = ENV["NOTESPRO_BASE_PRODUCT"]
  FREE_PRODUCT_ID = ENV["NOTESPRO_FREE_PRODUCT"]
  SUB_ACCOUNT_PRODUCT_ID = ENV["NOTESPRO_SUBACCOUNT_PRODUCT"]

  STRIPE_PK = ENV["NOTESPRO_STRIPE_PK"]
end
